language: dart
dist: xenial
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache

dart:
  # Install the latest stable release
  - stable
  # Install the latest beta release
  - beta
  # Install the latest dev release
  - dev
  # Install a specific stable release - 1.15.0
  - "1.15.0"
  # Install a specific dev release, using a partial download URL - 2.9.0-2.0.dev
  - "dev/release/2.9.0-2.0.dev"
  # Install a specific beta release, using a partial download URL - 2.9.0-2.0.beta
  - "beta/release/2.9.0-2.0.beta"

dart_task:
  - test: --platform vm
  - test: --platform dartium
  install_dartium: true

